CREATE TABLE MEMBER(
  ID VARCHAR(20) PRIMARY KEY
 ,  PW VARCHAR(20)  NULL
 , NAME VARCHAR(20) NOT NULL 
);

INSERT INTO member(ID,PW,NAME) VALUES('JA','5555','JAVA');
SELECT * FROM member;

CREATE TABLE MOVIE(
 MOVIE_CODE INT PRIMARY KEY AUTO_INCREMENT
, MOVIE_NAME VARCHAR(20) NOT NULL
, SEAT_CNT INT NOT NULL
);

INSERT INTO MOVIE(MOVIE_CODE,MOVIE_NAME,SEAT_CNT ) VALUES(1,'영화', 1);

CREATE TABLE SEAT(
 SEAT_CODE INT PRIMARY KEY AUTO_INCREMENT
, ROW_CODE VARCHAR(10) NOT NULL
, COL_CODE VARCHAR(10)  NOT NULL
, SEAT_DONE VARCHAR(10) NOT NULL
, MOVIE_CODE INT REFERENCES MOVIE(MOVIE_CODE) 
);

INSERT INTO SEAT(SEAT_CODE, ROW_CODE,COL_CODE,SEAT_DONE,MOVIE_CODE) 
VALUES(1,'1','1','2',1);

CREATE TABLE RESERVE_MOVIE(
 RESERVE_CODE INT PRIMARY KEY AUTO_INCREMENT
, ID INT NOT NULL REFERENCES MEMBER(ID)
, MOVIE_CODE INT NOT NULL REFERENCES MOVIE(MOVIE_CODE)
, SEAT_CODE INT NOT NULL REFERENCES SEAT(SEAT_CODE)
);







