
CREATE TABLE CAR_INFO(
   MODEL_NUMBER INT AUTO_INCREMENT PRIMARY KEY 
   , MODEL_NAME VARCHAR(20) NOT NULL UNIQUE
   , CAR_PRICE VARCHAR(20) NOT NULL
   , CAR_BRAND VARCHAR(20) NOT NULL
);

CREATE TABLE SALES_INFO(
	SALE_NUMBER INT AUTO_INCREMENT PRIMARY KEY
	, CUSTOMER_NAME VARCHAR(20) NOT NULL 
	, CUSTOMER_TEL VARCHAR(20) 
	, CAR_COLOR VARCHAR(20) NOT NULL
	, SALE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
	, MODEL_NUMBER INT NOT NULL REFERENCES CAR_INFO(MODEL_NUMBER)
);

INSERT INTO car_info
(
   CAR_BRAND
   , MODEL_NAME
   , CAR_PRICE
) 
VALUES(
   );
   
   
SELECT * FROM car_info;


INSERT INTO sales_info(
	CUSTOMER_NAME
	, CAR_COLOR
	, MODEL_NUMBER
	, CUSTOMER_TEL
)
VALUES(
	
);