-- 학급정보
CREATE TABLE CLASS_INFO(
	CLASS_CODE INT AUTO_INCREMENT PRIMARY KEY
	, CLASS_NAME VARCHAR(20) NOT NULL
	 
);

INSERT INTO CLASS_INFO VALUES(1,'자바반');
INSERT INTO CLASS_INFO VALUES(2,'디자인반');
INSERT INTO CLASS_INFO VALUES(3,'케드반');

SELECT * FROM CLASS_INFO; 

-- 학생 정보
CREATE TABLE STUDENT_INFO(
 STU_NUM INT AUTO_INCREMENT PRIMARY KEY
 , STU_NAME VARCHAR(20) NOT NULL
 , CLASS_CODE INT REFERENCES CLASS_INFO(CLASS_CODE)
);

INSERT INTO STUDENT_INFO VALUES (1, '김자바',1);
INSERT INTO STUDENT_INFO VALUES (2, '이자바',1);
INSERT INTO STUDENT_INFO VALUES (3, '박자바',1);
INSERT INTO STUDENT_INFO VALUES (4, '최자바',1);
INSERT INTO STUDENT_INFO VALUES (5, '정자바',1);

INSERT INTO STUDENT_INFO VALUES (6, '김디자인',2);
INSERT INTO STUDENT_INFO VALUES (7, '이디자인',2);
INSERT INTO STUDENT_INFO VALUES (8, '박디자인',2);
INSERT INTO STUDENT_INFO VALUES (9, '최디자인',2);
INSERT INTO STUDENT_INFO VALUES (10, '정디자인',2);

INSERT INTO STUDENT_INFO VALUES (11, '김케드',3);
INSERT INTO STUDENT_INFO VALUES (12, '이케드',3);
INSERT INTO STUDENT_INFO VALUES (13, '박케드',3);
INSERT INTO STUDENT_INFO VALUES (14, '최케드',3);
INSERT INTO STUDENT_INFO VALUES (15, '정케드',3);

SELECT * FROM STUDENT_INFO;
COMMIT;

SELECT * FROM board;
SELECT * FROM board_member;

-- 모든 게시글의 
-- 게시글 번호, 제목, 작성자명, 작성자 ID를 조회

SELECT BOARD_NUM
		, TITLE
		, MEMBER_ID
		, MEMBER_NAME
FROM board INNER JOIN board_member
ON WRITER = MEMBER_ID;

--  모든 학생의 학번, 소속 반이름, 학생명 조회

SELECT * FROM class_info;
SELECT * FROM student_info;

SELECT 
	STU_NUM 
	, CLASS_NAME
	, STU_NAME
FROM student_info S INNER JOIN class_info C
ON S.CLASS_CODE= C.CLASS_CODE;


 SELECT STU_NUM
        , STU_NAME
        , CLASS_NAME
FROM STUDENT_INFO S INNER JOIN CLASS_INFO C
ON S.CLASS_CODE= C. CLASS_CODE
WHERE S.CLASS_CODE=2
ORDER BY C.CLASS_CODE ASC, STU_NUM ASC;

CREATE TABLE STU_SCORE(
	SCORE_NUM INT AUTO_INCREMENT PRIMARY KEY
	, KOR_SCORE INT DEFAULT 0
	, ENG_SCORE INT DEFAULT 0
	, MATH_SCORE INT DEFAULT 0
	, STU_NUM INT REFERENCES student_info (STU_NUM)
);



SELECT KOR_SCORE, ENG_SCORE, MATH_SCORE 
FROM stu_score
WHERE STU_NUM=1;

SELECT * FROM stu_score;

DELETE FROM stu_score WHERE STU_NUM=1;

DELETE FROM stu_score WHERE SCORE_NUM=3;




