-- 학생 관리 프로그램 테이블
CREATE TABLE STU (
  STU_NO INT PRIMARY KEY
  , STU_NAME VARCHAR(10) NOT NULL
  , SCORE INT DEFAULT 0
  , KOR_SCORE INT DEFAULT 0
  , ENG_SCORE INT DEFAULT 0
  -- 아무 값도 안 넣었을 때 0 나옴
  , INTRO VARCHAR(50)
);

SELECT * FROM stu;